name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: bun dev
